### ISSUE TITLE
Criar uma área de resumo de eventos passados (SASIG)

### ISSUE THREAD

**Issue by ulmi** [OSGEO-PT/site#6]
Criar uma área de resumo de eventos passados (SASIG).

O pedro está a tratar do conteúdo.

**Comment by pedromap** [comment]
Estava a pensar naquele apanhado que fizemos na drive com os dados dos diversos SASIG (data, local, patrocinadores, programa, oradores, organização, etc)

**Comment by ghost** [comment]
Podia ser oportuno enviar para a lista um pedido de fotos de eventos
passados para compilar e criar galerias
Em 23/03/2015 11:00, "Pedro Pereira" notifications@github.com escreveu:

**Comment by pedromap** [comment]
Pedimos aos organizadores.
Em 23/03/2015 12:54, "osgeopt" notifications@github.com escreveu:

**Comment by ulmi** [comment]
area criada
